spring:
  application:
    name: productLine-service
    cloud:
      gateway:
        routes:
          - id: employeeModule
            uri: lb://productLine-service
            predicates:
              - Path=/api/product/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true